### ISSUE TITLE
Bitwarden File Send Question

### ISSUE THREAD

**Issue by jahvari** [johnduprey/BitwardenPS#15]
Docs/Update-BwSend.md

I've been trying to update a send and cannot seem to find a way to make the Update-BwSend command work with the ID. I have tried it a couple different ways. I must be doing something wrong.

![Capture1](https://user-images.githubusercontent.com/75337667/222760802-804ea849-c931-48b1-8d2d-d63f74a917f3.PNG)
![Capture2](https://user-images.githubusercontent.com/75337667/222760813-a1a99d42-9555-4354-9645-97cc4113f217.PNG)

https://bitwarden.com/help/vault-management-api/

These happen to be file sends and I noticed that the Bitwarden vault API for editing a send only supports text documents.
![Vault-Management-API-Bitwarden-Help-Center](https://user-images.githubusercontent.com/75337667/222760997-88295efe-d2b7-42fe-a6d3-261d4569a239.png)

I am not a script/programmer, but I am assuming this powershell module is only able to interact with the Vault Management API and not with the actual CLI .exe, as the command file supports adding file sends with the -f command.

![Capture](https://user-images.githubusercontent.com/75337667/222762628-edd9a557-dcf0-4f85-95e1-27c542e91cb9.PNG)

**Comment by JohnDuprey** [comment]
That's correct, we are only using the Vault Management API. If you need to send a file, you'll have to use the UI or the command line interface.
